#ifndef CONSTANTES_H
#define CONSTANTES_H

#define LARGEUR_TILE 175
#define HAUTEUR_TILE 44

#define LARGEUR_SPRITE1 150
#define HAUTEUR_SPRITE1 150

#define NOMBRE_BLOCS_LARGEUR 16
#define NOMBRE_BLOCS_HAUTEUR 29

#define WINDOW_SIZE_WIDTH 1200
#define WINDOW_SIZE_HIGH 650


#endif