#ifndef CONSTANTES_H
#define CONSTANTES_H

#define LARGEUR_TILE 175
#define HAUTEUR_TILE 44

#define LARGEUR_SPRITE 150
#define HAUTEUR_SPRITE 150

#define NOMBRE_BLOCS_LARGEUR 10
#define NOMBRE_BLOCS_HAUTEUR 58

#define WINDOW_SIZE_WIDTH 1200
#define WINDOW_SIZE_HEIGHT 650




#endif